source "http://rubygems.org"

gem "rspec", :require => "spec"
gem "cucumber"
gem "capybara"
gem "rspec-expectations"
gem "activesupport"
gem "win32-process"
gem "sys-proctable", :platforms => :mswin
gem "launchy"
